### ISSUE TITLE
Animation Player Tracks

### ISSUE THREAD

**Issue by taylorbrook** [taylorbrook/polyrhythmia#1]
Was able to find the delay effect tap time using the following script:

> extends Node
> 
> var delaytap1 = AudioServer.get_bus_effect(1,0).tap1_delay_ms
> 
> func _process(delta):
> 	print(delaytap1)

However I can't figure out how to not make this an animation track

**Comment by jseedev** [comment]
Fixed with a `export` keyword. Added set/get functions to make it work as expected.
